#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# It's important to keep lines from here down to "COPY . ." identical in all Dockerfiles
# to take advantage of Docker's build cache, to speed up local container builds
COPY "mssproto.sln" "mssproto.sln"

COPY "Web/WebMVC/WebMVC.csproj" "Web/WebMVC/WebMVC.csproj"

COPY "docker-compose.dcproj" "docker-compose.dcproj"

RUN dotnet restore "mssproto.sln"

COPY . .
WORKDIR /src/Web/WebMVC
RUN dotnet publish --no-restore -c Release -o /app

FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebMVC.dll"]
