version: '0.0'

services:
  
  mssproto-ek:
    container_name: mssproto-ek
    image: nshou/elasticsearch-kibana:latest

  mssproto-rabbitmq:
    container_name: mssproto-rabbitmq
    image: masstransit/rabbitmq

  mssproto-sqldb:
    container_name: mssproto-sqldb
    image: mcr.microsoft.com/mssql/server:2019-latest 

  mssproto-fe:
    image: ${REGISTRY:-mssproto}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile

  mssproto-test-service:
    image: ${REGISTRY:-mssproto}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/TestService/Dockerfile
