name: "mssproto"

services:
  
  mssproto-ek:
    container_name: mssproto-ek
    image: nshou/elasticsearch-kibana:latest

  mssproto-rabbitmq:
    container_name: mssproto-rabbitmq
    image: masstransit/rabbitmq

  mssproto-fe:
    image: ${REGISTRY:-mssdevlab}/mssproto:webmvc-${PLATFORM:-linux}-${TAG:-latest}
    container_name: mssproto-fe
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    secrets:
      - app_secret
    volumes:
      - mssproto-usersdata:/appdata
    depends_on:
      - mssproto-rabbitmq

  mssproto-vk-service:
    image: ${REGISTRY:-mssdevlab}/mssproto:vkservice-${PLATFORM:-linux}-${TAG:-latest}
    container_name: mssproto-vk-service
    build:
      context: .
      dockerfile: Services/VkService/Dockerfile
    secrets:
      - app_secret
    depends_on:
      - mssproto-rabbitmq

  mssproto-yt-service:
    image: ${REGISTRY:-mssdevlab}/mssproto:ytservice-${PLATFORM:-linux}-${TAG:-latest}
    container_name: mssproto-yt-service
    build:
      context: .
      dockerfile: Services/YtService/Dockerfile
    secrets:
      - app_secret
    depends_on:
      - mssproto-rabbitmq

  mssproto-test-ad-service:
    image: ${REGISTRY:-mssdevlab}/mssproto:testadservice-${PLATFORM:-linux}-${TAG:-latest}
    container_name: mssproto-test-ad-service
    build:
      context: .
      dockerfile: Services/TestAdService/Dockerfile
    depends_on:
      - mssproto-rabbitmq
      
volumes:
  mssproto-usersdata:
    external: false

secrets:
  app_secret:
    file: appsecrets.json
