version: '0.0'

services:

  invest-ek:
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "6601:5601"
      - "9200:9200"

  invest-rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  invest-sqldb:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - invest-sqldata:/var/opt/mssql

  invest-fe:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "6080:80"
      - "6443:443"
    depends_on:  
      - invest-sqldb

volumes:
  invest-sqldata:
    external: false
