version: '0.0'

services:
  
  invest-ek:
    container_name: invest-ek
    image: nshou/elasticsearch-kibana:latest

  invest-rabbitmq:
    container_name: invest-rabbitmq
    image: masstransit/rabbitmq

  invest-sqldb:
    container_name: invest-sqldb
    image: mcr.microsoft.com/mssql/server:2019-latest 

  invest-fe:
    image: ${REGISTRY:-invest}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile

  invest-test-service:
    image: ${REGISTRY:-invest}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/TestService/Dockerfile
